### ISSUE TITLE
result recurrent

### ISSUE THREAD

**Issue by Vencent-Won** [xujing1994/Explanability_bkd_gnn#1]
sorry to disturb, I try to recurrent the result of the graph classification. And I find that there is no trigger node mapping acquisition code.  So I try to replace them with  
```   pretrain_model.eval()
    G_trigger = nx.erdos_renyi_graph(num_trigger_nodes, args.density)
    # build explainer
    explainer = GNNExplainer(pretrain_model, feat_mask_type='scalar', lr=0.001)
    # 
    for idx in rand_backdoor_graph_idx:
        data = datas[idx]
        node_feat_mask, _ = explainer.explain_graph(data['x'], data['edge_index'])
        trigger_nodes = list(node_feat_mask.argsort()[:num_trigger_nodes].detach().cpu().numpy())```
however, there is nearly no attack effectiveness.

**Comment by 21151213732** [comment]
An error occurred while running the injected trigger code.Specific code：
    for i, data in enumerate(train_trigger_graphs):
        for j in range(len(trigger_list[i])-1):
            for k in range(j+1, len(trigger_list[i])):
                if (data[0].has_edges_between(trigger_list[i][j], trigger_list[i][k]) or data[0].has_edges_between(trigger_list[i][k], trigger_list[i][j])) \
                    and G_trigger.has_edge(j, k) is False:
                    ids = data[0].edge_ids(torch.tensor([trigger_list[i][j], trigger_list[i][k]]), torch.tensor([trigger_list[i][k], trigger_list[i][j]]))
                    data[0].remove_edges(ids)
                elif (data[0].has_edges_between(trigger_list[i][j], trigger_list[i][k]) or data[0].has_edges_between(trigger_list[i][k], trigger_list[i][j])) is False \
                    and G_trigger.has_edge(j, k):
                    data[0].add_edges(torch.tensor([trigger_list[i][j], trigger_list[i][k]]), torch.tensor([trigger_list[i][k], trigger_list[i][j]]))

Error display：
Traceback (most recent call last):
  File "D:/PycharmProjects/Explanability_bkd_gnn-master/main/graph_classification/attack.py", line 127, in <module>
    train_trigger_graphs, test_trigger_graphs, trigger, final_idx = inject_trigger(train_data, test_data, avg_nodes, args, config)
  File "D:\PycharmProjects\Explanability_bkd_gnn-master\util.py", line 73, in inject_trigger
    if (data[0].has_edges_between(trigger_list[i][j], trigger_list[i][k]) or data[0].has_edges_between(trigger_list[i][k], trigger_list[i][j])) \
  File "D:\Anaconda\envs\E-bkd\lib\site-packages\dgl\heterograph.py", line 2834, in has_edges_between
    raise DGLError('u contains invalid node IDs')
dgl._ffi.base.DGLError: u contains invalid node IDs

**Comment by 21151213732** [comment]
May I ask how the Mutagenicity_GCN file under the maad folder is generated?

**Comment by 21151213732** [comment]
> sorry to disturb, I try to recurrent the result of the graph classification. And I find that there is no trigger node mapping acquisition code. So I try to replace them with
> 
> ```
>     G_trigger = nx.erdos_renyi_graph(num_trigger_nodes, args.density)
>     # build explainer
>     explainer = GNNExplainer(pretrain_model, feat_mask_type='scalar', lr=0.001)
>     # 
>     for idx in rand_backdoor_graph_idx:
>         data = datas[idx]
>         node_feat_mask, _ = explainer.explain_graph(data['x'], data['edge_index'])
>         trigger_nodes = list(node_feat_mask.argsort()[:num_trigger_nodes].detach().cpu().numpy())```
> however, there is nearly no attack effectiveness.
> ```

Hello, is the problem solved? Did you replicate the code successfully？
